---
- name: add luigi repo
  command: >
    helm repo add phenomenal-helm
    https://phnmnl.github.io/helm-charts

- name: install luigi
  command: >
    helm upgrade
    --install
    --set image.tag="{{luigi_image_tag}}",ingress.domain="{{domain}}",ingress.hostname="{{hostname}}",resources.requests.memory="{{luigi_resource_req_memory}}",resources.requests.cpu="{{luigi_resource_req_cpu}}"
    "luigi"
    phenomenal-helm/luigi
