---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-pg-optimized
  namespace: storage-heketi
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://{{ heketi_endpoint }}"
  volumetype: {{volumetype}}
  volumeoptions:
    performance.quick-read off, performance.read-ahead off,
    performance.io-cache off, performance.stat-prefetch off,
    performance.low-prio-threads 32, performance.open-behind off,
    performance.write-behind off
mountOptions:
  - entry-timeout=0
  - attribute-timeout=0
