---
- name: install heapster
  command: >
   helm upgrade --install \
   --namespace kube-system \
   --version "{{ heapster_chart_version }}"
   "heapster-{{ heapster_chart_version }}"
   stable/heapster
