---
- name: Installs phenomenal services
  hosts: master
  gather_facts: "no"
  vars:
    # Services
    jupyter_include: "true"
    jupyter_hostname: "notebook"
    luigi_include: "true"
    luigi_hostname: "luigi"
    galaxy_include: "true"
    galaxy_hostname: "galaxy"
    galaxy_generated_key: "{{lookup('password', 'galaxy-api-key length=25 chars=ascii_letters')}}"
    dashboard_include: "true"
    dashboard_hostname: "dashboard"
    # Storage
    pvc_name: "galaxy-pvc"
    # Domain
    cloudflare_proxied: "false"
    proxied_suffix: ""
    # Logging
    no_sensitive_logging: "false"

  tasks:
    # Wait for all default kubernetes pods to be ready
    - name: Wait for all default kubernetes pods to be ready
      include_role:
        name: roles/wait-for-all-pods-ready

    # Galaxy
    - name: Galaxy
      include_role:
        name: roles/galaxy
      vars:
        galaxy_chart_version: "0.3.5"
        hostname: "{{galaxy_hostname}}{{proxied_suffix}}"
        galaxy_image_tag: ":rc_v17.09-pheno-lr_cv1.6.162"
        galaxy_admin_password: "generate-random-passw"
        galaxy_admin_email: "your @ email.com"
        galaxy_api_key: "{{galaxy_generated_key}}"
        galaxy_pvc: "{{pvc_name}}"
        postgres_pvc: "{{pvc_name}}"
        nologging: "{{no_sensitive_logging}}"
      when:
        galaxy_include | bool  == true

    # Jupyter
    - name: Jupyter
      include_role:
        name: roles/jupyter
      vars:
        jupyter_chart_version: "0.1.2"
        hostname: "{{jupyter_hostname}}{{proxied_suffix}}"
        jupyter_image_tag: ":v387f29b6ca83_cv0.4.9"
        jupyter_password: "generate-random-passw"
        jupyter_pvc: "{{pvc_name}}"
        jupyter_resource_req_cpu: "200m"
        jupyter_resource_req_memory: "1G"
        nologging: "{{no_sensitive_logging}}"
      when:
        jupyter_include | bool == true

    # Luigi
    - name: Install Luigi
      include_role:
        name: roles/luigi
      vars:
        luigi_chart_version: "0.1.2"
        luigi_image_tag: "dev_v2.6.0_cv0.1.7"
        luigi_username: "{{luigi_username}}"
        luigi_password: "{{luigi_password}}"
        hostname: "{{luigi_hostname}}{{proxied_suffix}}"
        luigi_resource_req_memory: "1G"
        luigi_resource_req_cpu: "200m"
      when:
        luigi_include | bool == true

    # Dashboard
    - name: Dashboard
      include_role:
        name: roles/kubernetes-dashboard
      vars:
        dashboard_username: "{{dashboard_username}}"
        dashboard_password: "{{dashboard_password}}"
        dashboard_host: "{{dashboard_hostname}}{{proxied_suffix}}.{{domain}}"
        nologging: "{{no_sensitive_logging}}"
      when:
        dashboard_include | bool == true

    # Heapster (for Dashboard)
    - name: Heapster (for Dashboard)
      include_role:
        name: roles/heapster
      when:
        dashboard_include | bool == true

    # Add demo-data to jupyter from repo
    - name: Add mtbls233 data
      include_role:
        name: roles/mtbls233-demo
      when:
        jupyter_include | bool == true

    #
    # Wait for services to be up
    #

    # Jupyter
    - name: "Wait for Jupyter notebook to be ready"
      uri:
        url: "http://{{jupyter_hostname}}{{proxied_suffix}}.{{domain}}"
      register: result
      until:
        result['status'] | default(0) == 200
      # Try for 20 minutes
      retries: 240
      delay: 5
      when:
        jupyter_include | bool == true

    # Luigi
    - name: "Wait for luigi to be responding)"
      uri:
        url: "http://{{luigi_hostname}}{{proxied_suffix}}.{{domain}}"
        user: "{{luigi_username}}"
        password: "{{luigi_password}}"
        force_basic_auth: yes
      register: result
      until:
        result['status'] | default(0) == 200
      # Try for 20 minutes
      retries: 240
      delay: 5
      when:
        luigi_include | bool == true

    # Galaxy
    - name: "Wait for galaxy to be responding (usually takes minutes)"
      uri:
        url: "http://{{galaxy_hostname}}{{proxied_suffix}}.{{domain}}"
      register: result
      until:
        result['status'] | default(0) == 200
      # Try for 20 minutes
      retries: 240
      delay: 5
      when:
        galaxy_include | bool == true
